// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ShSnNhQqKXxpCyEOmIIeBUfcBj7lspQ',
    appId: '1:57958510079:web:03f7cf200f1bf569630bca',
    messagingSenderId: '57958510079',
    projectId: 'musify-app-faa38',
    authDomain: 'musify-app-faa38.firebaseapp.com',
    storageBucket: 'musify-app-faa38.appspot.com',
    measurementId: 'G-MMW93Q9TPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuM30zW_uzH926GU2PagvR2rPKQnX8OU',
    appId: '1:57958510079:android:b4df7f6a394fa641630bca',
    messagingSenderId: '57958510079',
    projectId: 'musify-app-faa38',
    storageBucket: 'musify-app-faa38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbI4Yng6Fs0gKTnBuavw-QF62rxlZ2-14',
    appId: '1:57958510079:ios:f154d5b6a9d39b3f630bca',
    messagingSenderId: '57958510079',
    projectId: 'musify-app-faa38',
    storageBucket: 'musify-app-faa38.appspot.com',
    iosBundleId: 'com.example.musify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbI4Yng6Fs0gKTnBuavw-QF62rxlZ2-14',
    appId: '1:57958510079:ios:f154d5b6a9d39b3f630bca',
    messagingSenderId: '57958510079',
    projectId: 'musify-app-faa38',
    storageBucket: 'musify-app-faa38.appspot.com',
    iosBundleId: 'com.example.musify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0ShSnNhQqKXxpCyEOmIIeBUfcBj7lspQ',
    appId: '1:57958510079:web:192aeda290b4870f630bca',
    messagingSenderId: '57958510079',
    projectId: 'musify-app-faa38',
    authDomain: 'musify-app-faa38.firebaseapp.com',
    storageBucket: 'musify-app-faa38.appspot.com',
    measurementId: 'G-V1BX0X0465',
  );
}
